### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ibhavin** [angelvasa/AVXCAssets-Generator#2]
First of all this is fantastic and time saver.

I have followed your gif but in my case it is not working...I am using Xcode Version 7.3.1

**Comment by angelvasa** [comment]
Can you provide more details?
Like, Your image format, image name, folder name and path where you are saving 

Most probably you have space in some of this params.

**Comment by ibhavin** [comment]
@angelvasa  Here is the video: http://sendvid.com/s6tw0oua

I am using 512*512 size images and all pngs.

**Comment by angelvasa** [comment]
Strange!!

Can you please check your open project and the path where you are saving assets, are same or not?

**Comment by ibhavin** [comment]
@angelvasa  I have checked Assets.xcassets folder from project folder. There are all images but when I open my project the images are not displaying.

**In Project Folder:**
![screen shot 2016-06-13 at 11 05 54 am](https://cloud.githubusercontent.com/assets/16459948/15997821/0cad221e-3156-11e6-9cbb-ee5de6143ae9.png)

**In Project:**
![screen shot 2016-06-13 at 11 06 09 am](https://cloud.githubusercontent.com/assets/16459948/15997822/0cad3506-3156-11e6-97be-dadcfdc2ad9c.png)

**Comment by angelvasa** [comment]
Not an issue with AVXCAssets-Generator, May be your relative path issue.

Best way is to create new project and check with it.

**Comment by ibhavin** [comment]
@angelvasa  Thanks for your help: I have solved this issue, There were two Assets.xcassets folder. I have to take path of Assets.xcassets which was in another folder.

**Comment by angelvasa** [comment]
Not an issue with AVXCAssets-Generator
Closing this issue.
